{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyO7B7EUiK4T1QpZewYcQjuE",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/avanthika1302/GeminiHackathon/blob/main/photo_assistant_chatbot.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import streamlit as st\n",
        "import time, io\n",
        "import helper\n",
        "#from helper import generate_description, clean_json, insert_image_metadata, search_similar_places, answer_question_from_json\n",
        "import toml\n",
        "\n",
        "# --- Session state init ---\n",
        "if \"messages\" not in st.session_state:\n",
        "    st.session_state.messages = []\n",
        "if \"user_info\" not in st.session_state:\n",
        "    st.session_state.user_info = {}\n",
        "if \"user_history\" not in st.session_state:\n",
        "    st.session_state.user_history = []\n",
        "if \"last_image\" not in st.session_state:\n",
        "    st.session_state.last_image = None\n",
        "if \"last_ModelOP\" not in st.session_state:\n",
        "    st.session_state.last_ModelOP = None\n",
        "if \"show_upload\" not in st.session_state:\n",
        "    st.session_state.show_upload = True\n",
        "\n",
        "# Sidebar user session management\n",
        "st.sidebar.title(\"User Session\")\n",
        "\n",
        "if st.sidebar.button(\"Reset Session\"):\n",
        "    st.session_state.clear()\n",
        "    st.rerun()\n",
        "\n",
        "\n",
        "# Get user info\n",
        "if not st.session_state.user_info:\n",
        "    st.title(\"📸 Smart Photography Assistant\")\n",
        "    st.subheader(\"Tell us about you to get started\")\n",
        "    name = st.text_input(\"Your Name\", key=\"name_input\")\n",
        "    email = st.text_input(\"Your Email\", key=\"email_input\")\n",
        "    location = st.text_input(\"Location of interest\", key=\"loc_input\")\n",
        "\n",
        "    if st.button(\"Start Session\"):\n",
        "        if name and email and location:\n",
        "            #st.chat_message(\"Welcome \" + name )\n",
        "            st.session_state.user_info = {\n",
        "                \"name\": name,\n",
        "                \"email\": email,\n",
        "                \"location\": location\n",
        "            }\n",
        "            st.rerun()\n",
        "        else:\n",
        "            st.warning(\"Please fill in all fields.\")\n",
        "    st.stop()\n",
        "\n",
        "# --- Main Chat UI ---\n",
        "# Display chat history\n",
        "\n",
        "st.title(\"📸 Smart Photography Assistant\")\n",
        "st.subheader(\"Welcome \" + st.session_state.user_info[\"name\"]+\"!\")\n",
        "st.markdown(\"Hi! I'm your Photo Assistant 🤖. Here's what I can do:\")\n",
        "st.markdown(\"\"\"\n",
        "                - 📝 Describe an uploaded photo\n",
        "                - 📸 Social media captions and tags\n",
        "                - Ideal weather for a perfect picture\n",
        "                - 🔁 Show similar images\n",
        "                - 📍 Suggest nearby photo spots\n",
        "                - 🔄 Clear all and start over\n",
        "                Just type your option and I'll help!\n",
        "                \"\"\")\n",
        "\n",
        "for msg in st.session_state.messages:\n",
        "    with st.chat_message(msg[\"role\"]):\n",
        "        st.markdown(msg[\"content\"])\n",
        "\n",
        "# Handle new user message\n",
        "uploaded_file = None\n",
        "\n",
        "if st.session_state.show_upload:\n",
        "    uploaded_file = st.file_uploader(\"Upload a photo to proceed\", type=[\"jpg\", \"jpeg\", \"png\"], key=\"file_uploader\")\n",
        "\n",
        "    if uploaded_file:\n",
        "        st.session_state.last_image = uploaded_file.read()\n",
        "        st.info(\"Uploading and analyzing your photo...\")\n",
        "        with st.spinner(\"Working on uploading...\"):\n",
        "            time.sleep(10)  # simulate processing\n",
        "\n",
        "        ModelOP = helper.generate_description(st.session_state.last_image, st.session_state.user_info[\"location\"]).text\n",
        "        insights = helper.clean_json(ModelOP)\n",
        "\n",
        "        #Place holder for uploading an image\n",
        "        st.session_state.last_ModelOP = insights\n",
        "        st.session_state.messages.append({\n",
        "            \"role\": \"assistant\",\n",
        "            \"content\": \"Thanks for uploading!\"\n",
        "        })\n",
        "        st.session_state.show_upload = False\n",
        "\n",
        "if st.session_state.last_image != None:\n",
        "    st.image(io.BytesIO(st.session_state.last_image), caption=\"Your uploaded image\", use_container_width=True)#response = \"Upload feature enabled! Please upload your photo now.\"\n",
        "\n",
        "\n",
        "user_input = st.chat_input(\"What would you like to do?\", key=\"chat_box\")\n",
        "\n",
        "if user_input is not None and st.session_state.last_ModelOP is not None:\n",
        "    with st.spinner(\"Model responding...\"):\n",
        "        # simulate delay or processing\n",
        "        time.sleep(5)\n",
        "\n",
        "    st.session_state.messages.append({\"role\": \"user\", \"content\": user_input})\n",
        "\n",
        "    # Handle commands\n",
        "    cmd = user_input.lower()\n",
        "    response = \"\"\n",
        "\n",
        "    if \"start\" in cmd or \"reset\" in cmd:\n",
        "        st.session_state.clear()\n",
        "        st.rerun()\n",
        "    elif \"similar\" in cmd:\n",
        "        response = \"Here are some similar photo's I found...\"\n",
        "\n",
        "        urls = helper.search_similar_places(st.session_state.last_ModelOP,st.session_state.user_info[\"location\"])\n",
        "        for url in urls:\n",
        "          st.image(url['Imageurl'], caption=\"Your uploaded image\", use_container_width=True)\n",
        "    elif \"upload\" in cmd:\n",
        "        response = \"Upload a pic...\"\n",
        "        st.session_state.show_upload = True\n",
        "    else:\n",
        "        #st.session_state.show_upload = True\n",
        "        response = \"response from model\"\n",
        "\n",
        "    st.session_state.messages.append({\"role\": \"assistant\", \"content\": response})\n",
        "    st.rerun()  # Only needed once at the end to reflect both messages"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        },
        "id": "XkhUg55KQRxQ",
        "outputId": "67a907b9-b7f6-4057-aa11-accc6b87af0d"
      },
      "execution_count": 5,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2025-04-24 03:35:32.576 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.576 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.577 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.578 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.579 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.579 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.580 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.581 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.582 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.582 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.583 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.584 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.585 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.586 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.586 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.587 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.588 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.588 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.589 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.589 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.590 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.591 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.591 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.592 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.593 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.593 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.593 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.594 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.594 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.597 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.597 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.597 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.598 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.598 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.599 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.599 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.600 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.600 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.600 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.601 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.601 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.602 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.602 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.603 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-24 03:35:32.603 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
          ]
        },
        {
          "output_type": "error",
          "ename": "KeyError",
          "evalue": "'name'",
          "traceback": [
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
            "\u001b[0;31mKeyError\u001b[0m                                  Traceback (most recent call last)",
            "\u001b[0;32m<ipython-input-5-7247decebab8>\u001b[0m in \u001b[0;36m<cell line: 0>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     52\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     53\u001b[0m \u001b[0mst\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtitle\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"📸 Smart Photography Assistant\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 54\u001b[0;31m \u001b[0mst\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msubheader\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Welcome \"\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0mst\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msession_state\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0muser_info\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m\"name\"\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m+\u001b[0m\u001b[0;34m\"!\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     55\u001b[0m \u001b[0mst\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmarkdown\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Hi! I'm your Photo Assistant 🤖. Here's what I can do:\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     56\u001b[0m st.markdown(\"\"\"\n",
            "\u001b[0;31mKeyError\u001b[0m: 'name'"
          ]
        }
      ]
    }
  ]
}